// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _CancelStockEp } from '../src/api/cancelStock';
import type { default as _DeleteItemEp } from '../src/api/deleteItem';
import type { default as _GetAuditItemsEp } from '../src/api/getAuditItems';
import type { default as _GetItemHistoryEp } from '../src/api/getItemHistory';
import type { default as _GetItemsEp } from '../src/api/getItems';
import type { default as _GetLowStockEp } from '../src/api/getLowStock';
import type { default as _GetStockLogsEp } from '../src/api/getStockLogs';
import type { default as _GetTodayLogsEp } from '../src/api/getTodayLogs';
import type { default as _RecordStockEp } from '../src/api/recordStock';
import type { default as _SaveAuditEp } from '../src/api/saveAudit';

type _CancelStockCfg = typeof _CancelStockEp;
export type CancelStockInputType = NonNullable<_CancelStockCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CancelStockCfg['execute']>[0]['input'];
export type CancelStockOutputType = Awaited<ReturnType<_CancelStockCfg['execute']>>;
export const cancelStock = createCaller<CancelStockInputType, CancelStockOutputType>('cancelStock');

type _DeleteItemCfg = typeof _DeleteItemEp;
export type DeleteItemInputType = NonNullable<_DeleteItemCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteItemCfg['execute']>[0]['input'];
export type DeleteItemOutputType = Awaited<ReturnType<_DeleteItemCfg['execute']>>;
export const deleteItem = createCaller<DeleteItemInputType, DeleteItemOutputType>('deleteItem');

type _GetAuditItemsCfg = typeof _GetAuditItemsEp;
export type GetAuditItemsInputType = NonNullable<_GetAuditItemsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAuditItemsCfg['execute']>[0]['input'];
export type GetAuditItemsOutputType = Awaited<ReturnType<_GetAuditItemsCfg['execute']>>;
export const getAuditItems = createCaller<GetAuditItemsInputType, GetAuditItemsOutputType>('getAuditItems');

type _GetItemHistoryCfg = typeof _GetItemHistoryEp;
export type GetItemHistoryInputType = NonNullable<_GetItemHistoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetItemHistoryCfg['execute']>[0]['input'];
export type GetItemHistoryOutputType = Awaited<ReturnType<_GetItemHistoryCfg['execute']>>;
export const getItemHistory = createCaller<GetItemHistoryInputType, GetItemHistoryOutputType>('getItemHistory');

type _GetItemsCfg = typeof _GetItemsEp;
export type GetItemsInputType = NonNullable<_GetItemsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetItemsCfg['execute']>[0]['input'];
export type GetItemsOutputType = Awaited<ReturnType<_GetItemsCfg['execute']>>;
export const getItems = createCaller<GetItemsInputType, GetItemsOutputType>('getItems');

type _GetLowStockCfg = typeof _GetLowStockEp;
export type GetLowStockInputType = NonNullable<_GetLowStockCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLowStockCfg['execute']>[0]['input'];
export type GetLowStockOutputType = Awaited<ReturnType<_GetLowStockCfg['execute']>>;
export const getLowStock = createCaller<GetLowStockInputType, GetLowStockOutputType>('getLowStock');

type _GetStockLogsCfg = typeof _GetStockLogsEp;
export type GetStockLogsInputType = NonNullable<_GetStockLogsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetStockLogsCfg['execute']>[0]['input'];
export type GetStockLogsOutputType = Awaited<ReturnType<_GetStockLogsCfg['execute']>>;
export const getStockLogs = createCaller<GetStockLogsInputType, GetStockLogsOutputType>('getStockLogs');

type _GetTodayLogsCfg = typeof _GetTodayLogsEp;
export type GetTodayLogsInputType = NonNullable<_GetTodayLogsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTodayLogsCfg['execute']>[0]['input'];
export type GetTodayLogsOutputType = Awaited<ReturnType<_GetTodayLogsCfg['execute']>>;
export const getTodayLogs = createCaller<GetTodayLogsInputType, GetTodayLogsOutputType>('getTodayLogs');

type _RecordStockCfg = typeof _RecordStockEp;
export type RecordStockInputType = NonNullable<_RecordStockCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RecordStockCfg['execute']>[0]['input'];
export type RecordStockOutputType = Awaited<ReturnType<_RecordStockCfg['execute']>>;
export const recordStock = createCaller<RecordStockInputType, RecordStockOutputType>('recordStock');

type _SaveAuditCfg = typeof _SaveAuditEp;
export type SaveAuditInputType = NonNullable<_SaveAuditCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAuditCfg['execute']>[0]['input'];
export type SaveAuditOutputType = Awaited<ReturnType<_SaveAuditCfg['execute']>>;
export const saveAudit = createCaller<SaveAuditInputType, SaveAuditOutputType>('saveAudit');


export const api = {
  cancelStock,
  deleteItem,
  getAuditItems,
  getItemHistory,
  getItems,
  getLowStock,
  getStockLogs,
  getTodayLogs,
  recordStock,
  saveAudit,
};
